services:
  # Telegram Bot Service
  - type: web
    name: telegram-bot
    env: python
    plan: starter  # или другой план по вашим потребностям
    buildCommand: pip install -r requirements.txt
    startCommand: python scripts/start_bot.py --webhook --port $PORT
    envVars:
      - key: BOT_TOKEN
        sync: false  # Установите в Render Dashboard
      - key: WEBHOOK_URL
        value: https://telegram-bot.onrender.com  # Замените на ваш URL
      - key: WEBHOOK_PORT
        value: "8443"
      - key: ENVIRONMENT
        value: production
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: TZ
        value: UTC
    autoDeploy: true
    disk:
      name: data-disk
      mountPath: /opt/render/project/src/data
      sizeGB: 1
    healthCheckPath: /health
    
  # Render.com конфигурация для DailyCheck Bot Dashboard v4.0.1
services:
  - type: web
    name: dailycheck-dashboard-v4
    env: python
    plan: free
    
    # Build команды
    buildCommand: |
      echo "🚀 Устанавливаем зависимости для DailyCheck Bot Dashboard v4.0.1..."
      pip install --upgrade pip
      pip install -r requirements-web.txt || pip install fastapi uvicorn python-dotenv
      echo "✅ Зависимости установлены"
    
    # КРИТИЧНО: Используем ИСПРАВЛЕННУЮ версию с красивой HTML
    startCommand: python scripts/start_web_fixed.py
    
    # Переменные окружения
    envVars:
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
    
    # Health check настройки
    healthCheckPath: /health
    
    # Автоматический деплой при изменениях
    autoDeploy: true
    
    # Настройки ресурсов
    disk:
      name: data
      size: 1GB
      mountPath: /app/data
    
    # Дополнительные настройки
    buildFilter:
      paths:
        - scripts/start_web_fixed.py
        - requirements-web.txt
        - render.yaml
      ignoredPaths:
        - main.py
        - scripts/start_web.py  # Игнорируем старую версию
        - "*.md"
        - "*.log"
